export default function AboutSection() {
  return (
    <section id="about" className="w-full py-24 md:py-32 px-8 md:px-16 lg:px-24 bg-background">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-16 md:mb-24">
          <p className="label-text mb-6">Fondée 2015</p>
          <p className="label-text mb-4">Directrice générale et créative : Leila Boutaleb</p>
        </div>

        {/* Main text */}
        <div className="space-y-8 md:space-y-12 text-sm md:text-base leading-[1.8] font-sans text-foreground">
          <p>
            INTERLOFT EST UNE MAISON DE DESIGN CONTEMPORAIN FONDÉE À CASABLANCA EN 2015. LEILA BOUTALEB, DIRECTRICE GÉNÉRALE ET CRÉATIVE, SÉLECTIONNE AVEC SOIN CHAQUE PIÈCE DE MOBILIER ET D&APOS;OBJETS PRÉSENTÉS PAR INTERLOFT. SA PERSPECTIVE CURATORIALE EN MATIÈRE DE DESIGN, DE MEUBLES, D&APOS;ÉCLAIRAGE ET D&APOS;OBJETS PEUT ÊTRE DÉCRITE COMME INTEMPORELLE, LUXUEUSE ET MINIMALISTE, BIEN QU&APOS;ELLE ÉCHAPPE À TOUTE CATÉGORISATION FACILE. LES CLIENTS DU MONDE ENTIER VIENNENT À INTERLOFT POUR TROUVER DES PIÈCES EXCLUSIVES ET UNIQUES, TOUTES PRODUITES SELON LEURS SPÉCIFICATIONS.
          </p>

          <p>
            INTERLOFT REPRÉSENTE UNE SÉLECTION DE DESIGNERS ET D&APOS;ARTISANS CONTEMPORAINS, DONT LES PIÈCES REFLÈTENT LA RICHESSE DU PATRIMOINE MAROCAIN COMBINÉE À UN LANGAGE DESIGN RÉSOLUMENT MODERNE. CHAQUE OBJET EST PENSÉ COMME UNE DÉCLARATION D&APOS;INTENTION, OÙ LA FORME ET LA FONCTION S&APOS;ENTRELACENT POUR CRÉER DES ESPACES QUI INSPIRENT LA CONTEMPLATION ET LE BIEN-ÊTRE.
          </p>

          <p>
            LA MARQUE SUIT UNE PHILOSOPHIE DE CRÉATION ARTISANALE OÙ CHAQUE DÉTAIL EST MÉTICULEUSEMENT CONSIDÉRÉ. LES MATÉRIAUX SÉLECTIONNÉS — LIN NATUREL, BOIS MASSIFS, MÉTAUX NOBLES — SONT TRAVAILLÉS AVEC UNE RIGUEUR SANS COMPROMIS. LE RÉSULTAT EST UNE COLLECTION DE MEUBLES ET D&APOS;OBJETS QUI INCARNENT LA TIMELESSNESS, CONJUGUANT TRADITION ARTISANALE ET MINIMALISME CONTEMPORAIN.
          </p>

          <p>
            INTERLOFT OFFRE UNE EXPÉRIENCE CURATORIALE PERSONNALISÉE À SES CLIENTS. PAR UN PROTOCOLE PRIVÉ ET SUR RENDEZ-VOUS, CHAQUE VISITEUR EST IMMERGÉ DANS L&APOS;UNIVERS ESTHÉTIQUE DE LA MAISON, DÉCOUVRANT DES PIÈCES QUI RÉSONNENT AVEC LEUR VISION PERSONNELLE DE L&APOS;HABITAT MODERNE.
          </p>
        </div>
      </div>
    </section>
  )
}
